[package]
name = "mvm"
version = "0.1.0"
authors = ["ear7h <julio.grillo98@gmail.com>"]
edition = "2018"


[[bin]]
name = "mvm"
path = "src/mvm.rs"

[[bin]]
name = "mas"
path = "src/mas.rs"



[dependencies]
